include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "**.mocks.dart"
    - lib/generated_plugin_registrant.dart
    - lib/src/configs/l10n/**
    - example/**
    - lib/src/modules/todo_module/configs/grpc/**

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    public_member_api_docs: false
    always_specify_types: true
    lines_longer_than_80_chars: true
    sort_pub_dependencies: false