# sources: List of Strings or Map, Optional. The set of files within the package which make up this target.
# generate_for: List of String or Map, Optional:. The subset of files within the target's sources which should have this Builder applied. See sources configuration above for how to configure this.
# see more is https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md, https://github.com/dart-lang/build/blob/master/build_config/README.md
targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - test/**.dart
      - integration_test/**.dart
    builders:
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
          - integration_test/**.dart
