name: flutter_starter_kit
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0-beta+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  image_picker_web: ^2.1.1
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  firebase_performance: ^0.7.1+1
  firebase_analytics: ^9.1.8
  dio_firebase_performance: ^0.3.0
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  grpc: ^3.0.2
  get: ^4.6.5

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  build_runner: ^2.1.11
  mockito: ^5.2.0
  lint: ^1.8.2
  faker: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
