default_platform(:ios)

DEVELOPER_APP_ID = "tee.theeraporn@hugeman.co"
DEVELOPER_APP_IDENTIFIER = "com.hugeman.flutterstarterkit"
PROVISIONING_PROFILE_SPECIFIER = "match AppStore com.hugeman.flutterstarterkit"
TEMP_KEYCHAIN_USER = "tee.theeraporn@hugeman.co"
TEMP_KEYCHAIN_PASSWORD = "hugeman123"
TEST_NAME = "test-cert.keychain-db"
TEST_PASS = "hugeman123"


platform :ios do
  lane :test do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD

    delete_keychain(
        name: "test-cert.keychain-db"
      ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")

      create_keychain(
          name: "test-cert.keychain-db",
          password: "hugeman123",
          unlock: false,
          timeout: false
        )

    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )

#     gym(
#       configuration: "Release",
#       workspace: "Runner.xcworkspace",
#       scheme: "Runner",
#       export_method: "app-store",
#       export_options: {
#         provisioningProfiles: {
#             DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
#         }
#       }
#     )
#
#     pilot(
#       apple_id: "#{DEVELOPER_APP_ID}",
#       app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
#       skip_waiting_for_build_processing: true,
#       skip_submission: true,
#       distribute_external: false,
#       notify_external_testers: false,
#       ipa: "./Runner.ipa"
#     )

    delete_temp_keychain(keychain_name)
  end
end