FROM opensecurity/mobile-security-framework-mobsf

WORKDIR /home/mobsf/Mobile-Security-Framework-MobSF

COPY "entrypoint.sh" "/home/mobsf/Mobile-Security-Framework-MobSF/entrypoint_github.sh"

ENTRYPOINT ["/home/mobsf/Mobile-Security-Framework-MobSF/entrypoint_github.sh"]

CMD ["--help"]
