name: Project workflow

on: [ push, pull_request ]

jobs:
  fluter_analyze_test:
    name: Run flutter test, analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
        # gen l10n
      - name: Analyze project source
        run: flutter analyze
      - name: Test (Unit test & Widjet test)
        run: flutter test --coverage
        # gen output test coverage
        # gen mock file
      - name: Run tests
        run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [ fluter_analyze_test ]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Clean project
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
        # gen l10n
      - name: Build file .ipa
        run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [ fluter_analyze_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Clean project
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
        # gen l10n
      - name: Build file .aab
        run: flutter build appbundle

  build_web:
    name: Build Flutter (Web)
    needs: [ fluter_analyze_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Clean project
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get
        # gen l10n
      - name: Build web
        run: flutter build web
