name: CI/CD fastlane for Android

on:
  push:
#  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Create file .env
        run: |
          cat << EOF >> .env
          API_URL=${{ secrets.API_URL_DEV }}
          SSR_URL=${{ secrets.SSR_URL }}
          GRPC_WEB_SCHEME=${{ secrets.GRPC_WEB_SCHEME }}
          GRPC_WEB_DOMAIN=${{ secrets.GRPC_WEB_DOMAIN }}
          GRPC_WEB_PORT=${{ secrets.GRPC_WEB_PORT }}
          GRPC_MOBILE_DOMAIN=${{ secrets.GRPC_MOBILE_DOMAIN }}
          GRPC_MOBILE_PORT=${{ secrets.GRPC_MOBILE_PORT }}
          EOF
      - name: Create file .env-cicd
        run: |
          cat << EOF >> .env-cicd
          FASTLANE_SLACK_WEB_HOOK=${{ secrets.FASTLANE_SLACK_WEB_HOOK }}
          FASTLANE_SLACK_CHANNEL=${{ secrets.FASTLANE_SLACK_CHANNEL }}
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID=${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID }}
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS=${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS }}
          APP_BUNDLE_ID=${{ secrets.APP_BUNDLE_ID }}
          APPLE_ID=${{ secrets.APPLE_ID }}
          APPLE_ITC_TEAM_ID=${{ secrets.APPLE_ITC_TEAM_ID }}
          APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}
          FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_SERVICES_AC_JSON_DATA=${{ secrets.PLAY_STORE_CREDENTIALS }}
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER=${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
          EOF
      - name: Create file google-services.json
        run: |
          cd android/app; cat << EOF >> google-services.json
          ${{ secrets.GOOGLE_SERVICES_ANDROID }}
          EOF
      - name: Create file encode-upload-keystore.jks
        run: |
          cd android; cat << EOF >> encode-upload-keystore.jks
          ${{ secrets.UPLOAD_KEYSTORE }}
          EOF
      - name: Create file upload-keystore.jks
        run: base64 -d android/encode-upload-keystore.jks > android/upload-keystore.jks
      - name: Create file play-store-credentials.json
        run: |
          cat << EOF >> play-store-credentials.json
          ${{ secrets.PLAY_STORE_CREDENTIALS }}
          EOF
      - name: Create file key.properties
        run: |
          cd android; cat << EOF >> key.properties
          ${{ secrets.KEY_PROPERTIES_ANDROID }}
          EOF
      - name: Install dependencies
        run: make project/install/package
      - name: Generate l10n
        run: make l10n/generate
      - name: Generate mock file for test
        run: make test/generate/mock-file
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
      - name: Print new build number and run number
        run: echo "Build number is $BUILD_NUMBER, $GITHUB_RUN_NUMBER"
      - name: Increate version code
        run: perl -i -pe 's/^((version:\s+\d+\.\d+\.\d+\+)|(version:\s+\d+\.\d+\.\d+\-\w+\+))(\d+)$/$1.('$GITHUB_RUN_NUMBER')/e' pubspec.yaml
      - uses: actions/cache@v2
        id: file-env
        with:
          path: ./.env
          key: file-env
      - uses: actions/cache@v2
        id: file-env-cicd
        with:
          path: ./.env-cicd
          key: file-env-cicd
      - uses: actions/cache@v2
        id: file-env-google-service-android
        with:
          path: ./android/app/google-services.json
          key: file-env-google-service-android
      - uses: actions/cache@v2
        id: file-env-upload-keystore
        with:
          path: ./android/upload-keystore.jks
          key: file-env-upload-keystore
      - uses: actions/cache@v2
        id: file-env-play-store
        with:
          path: ./play-store-credentials.json
          key: file-env-play-store
      - uses: actions/cache@v2
        id: file-env-key-property
        with:
          path: ./android/key.properties
          key: file-env-key-property
      - uses: actions/cache@v2
        id: file-flutter-plugins
        with:
          path: ./.flutter-plugins
          key: file-flutter-plugins
      - uses: actions/cache@v2
        id: file-flutter-plugins-dependency
        with:
          path: ./.flutter-plugins-dependencies
          key: file-flutter-plugins-dependency
      - uses: actions/cache@v2
        id: file-flutter-packages
        with:
          path: ./.packages
          key: file-flutter-packages
      - uses: actions/cache@v2
        id: file-dart-tool
        with:
          path: ./.dart_tool
          key: file-dart-tool
      - uses: actions/cache@v2
        id: file-l10n
        with:
          path: ./lib/src/configs/l10n
          key: file-l10n

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/cache@v2
        id: file-env
        with:
          path: ./.env
          key: file-env
      - uses: actions/cache@v2
        id: file-env-cicd
        with:
          path: ./.env-cicd
          key: file-env-cicd
      - uses: actions/cache@v2
        id: file-env-google-service-android
        with:
          path: ./android/app/google-services.json
          key: file-env-google-service-android
      - uses: actions/cache@v2
        id: file-env-upload-keystore
        with:
          path: ./android/upload-keystore.jks
          key: file-env-upload-keystore
      - uses: actions/cache@v2
        id: file-env-play-store
        with:
          path: ./play-store-credentials.json
          key: file-env-play-store
      - uses: actions/cache@v2
        id: file-env-key-property
        with:
          path: ./android/key.properties
          key: file-env-key-property
      - uses: actions/cache@v2
        id: file-flutter-plugins
        with:
          path: ./.flutter-plugins
          key: file-flutter-plugins
      - uses: actions/cache@v2
        id: file-flutter-plugins-dependency
        with:
          path: ./.flutter-plugins-dependencies
          key: file-flutter-plugins-dependency
      - uses: actions/cache@v2
        id: file-flutter-packages
        with:
          path: ./.packages
          key: file-flutter-packages
      - uses: actions/cache@v2
        id: file-dart-tool
        with:
          path: ./.dart_tool
          key: file-dart-tool
      - uses: actions/cache@v2
        id: file-l10n
        with:
          path: ./lib/src/configs/l10n
          key: file-l10n
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'build_file_for_app_distribution'
          subdirectory: 'android'
      - uses: actions/cache@v2
        id: file-apk
        with:
          path: ./build/app/outputs/apk/release/app-release.apk
          key: file-apk
      - uses: actions/cache@v2
        id: file-gradle
        with:
          path: ./android/.gradle
          key: file-gradle
      - uses: actions/cache@v2
        id: file-gradlew
        with:
          path: ./android/gradlew
          key: file-gradlew
      - uses: actions/cache@v2
        id: file-gradlew-bat
        with:
          path: ./android/gradlew.bat
          key: file-gradlew-bat
      - uses: actions/cache@v2
        id: file-local-property
        with:
          path: ./android/local.properties
          key: file-local-property

  test_lab:
    needs: [ setup, build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/cache@v2
        id: file-env
        with:
          path: ./.env
          key: file-env
      - uses: actions/cache@v2
        id: file-env-cicd
        with:
          path: ./.env-cicd
          key: file-env-cicd
      - uses: actions/cache@v2
        id: file-env-google-service-android
        with:
          path: ./android/app/google-services.json
          key: file-env-google-service-android
      - uses: actions/cache@v2
        id: file-env-upload-keystore
        with:
          path: ./android/upload-keystore.jks
          key: file-env-upload-keystore
      - uses: actions/cache@v2
        id: file-env-play-store
        with:
          path: ./play-store-credentials.json
          key: file-env-play-store
      - uses: actions/cache@v2
        id: file-env-key-property
        with:
          path: ./android/key.properties
          key: file-env-key-property
      - uses: actions/cache@v2
        id: file-flutter-plugins
        with:
          path: ./.flutter-plugins
          key: file-flutter-plugins
      - uses: actions/cache@v2
        id: file-flutter-plugins-dependency
        with:
          path: ./.flutter-plugins-dependencies
          key: file-flutter-plugins-dependency
      - uses: actions/cache@v2
        id: file-flutter-packages
        with:
          path: ./.packages
          key: file-flutter-packages
      - uses: actions/cache@v2
        id: file-dart-tool
        with:
          path: ./.dart_tool
          key: file-dart-tool
      - uses: actions/cache@v2
        id: file-l10n
        with:
          path: ./lib/src/configs/l10n
          key: file-l10n
      - uses: actions/cache@v2
        id: file-gradle
        with:
          path: ./android/.gradle
          key: file-gradle
      - uses: actions/cache@v2
        id: file-gradlew
        with:
          path: ./android/gradlew
          key: file-gradlew
      - uses: actions/cache@v2
        id: file-gradlew-bat
        with:
          path: ./android/gradlew.bat
          key: file-gradlew-bat
      - uses: actions/cache@v2
        id: file-local-property
        with:
          path: ./android/local.properties
          key: file-local-property
      - run: la -la android
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'test_lab'
          subdirectory: 'android'

  mobSF:
    needs: [ setup, build, test_lab ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: file-apk
        with:
          path: ./build/app/outputs/apk/release/app-release.apk
          key: file-apk
      - name: Run mobSF
        env:
          MOBSF_URL: ${{ secrets.MOBSF_URL }}
          MOBSF_API_KEY: ${{ secrets.MOBSF_API_KEY }}
        run: export MOBSF_URL=$MOBSF_URL; export MOBSF_API_KEY=$MOBSF_API_KEY; export INPUT_FILE_NAME='build/app/outputs/apk/release/app-release.apk'; make mobsf/run



      # test lab
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@master
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#      - uses: maierj/fastlane-action@v2.0.1
#        with:
#          lane: 'test_lab'
#          subdirectory: 'android'
# app distribute
#      - uses: maierj/fastlane-action@v2.0.1
#        with:
#          lane: 'app_distribution_group_developer'
#          subdirectory: 'android'
#        env:
#          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID: ${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID }}
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
## play store
#      - uses: maierj/fastlane-action@v2.0.1
#        with:
#          lane: 'beta'
#          subdirectory: 'android'


