name: CI/CD fastlane for iOS

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Create file .env
        run: |
          cat << EOF >> .env
          API_URL=${{ secrets.API_URL_DEV }}
          FASTLANE_SLACK_WEB_HOOK=${{ secrets.FASTLANE_SLACK_WEB_HOOK }}
          FASTLANE_SLACK_CHANNEL=${{ secrets.FASTLANE_SLACK_CHANNEL }}
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID=${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID }}
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS=${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS }}
          APP_BUNDLE_ID=${{ secrets.APP_BUNDLE_ID }}
          APPLE_ID=${{ secrets.APPLE_ID }}
          APPLE_ITC_TEAM_ID=${{ secrets.APPLE_ITC_TEAM_ID }}
          APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}
          APPLE_PROVISIONING_PROFILE_DISTRIBUTE=${{ secrets.APPLE_PROVISIONING_PROFILE_DISTRIBUTE }}
          APPLE_PROVISIONING_PROFILE_ADHOC=${{ secrets.APPLE_PROVISIONING_PROFILE_ADHOC }}
          GRPC_HOST=${{ secrets.GRPC_HOST }}
          GRPC_PORT=${{ secrets.GRPC_PORT }}
          GRPC_SCHEME=${{ secrets.GRPC_SCHEME }}
          FASTLANE_FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_SERVICES_AC_JSON_DATA=${{ secrets.PLAY_STORE_CREDENTIALS }}
          GIT_URL=${{ secrets.GIT_URL }}
          MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME=${{ secrets.MATCH_USERNAME }}
          FASTLANE_SESSION=${{ secrets.FASTLANE_SESSION }}
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER=${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
          APP_BUNDLE_ID=${{ secrets.APP_BUNDLE_ID }}
          KEYCHAIN_PASSWORD=${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH=/Users/runner/Library/Keychains/fastlane_tmp_keychain-db
          APPLE_PASSWORD=${{ secrets.APPLE_PASSWORD }}
          APP_STORE_CONNECT_AUTH_KEY_ID=${{ secrets.APP_STORE_CONNECT_AUTH_KEY_ID}}
          APP_STORE_CONNECT_AUTH_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_AUTH_ISSUER_ID }}
          EOF
      - name: Create file GoogleService-Info.plist
        run: |
          cd ios; cat << EOF >> GoogleService-Info.plist
          ${{ secrets.GOOGLE_SERVICE_IOS }}
          EOF
      - name: Create file exportOptions.plist
        run: |
          cd ios; cat << EOF >> exportOptions.plist
          ${{ secrets.EXPORT_OPTIONS_PLIST }}
          EOF
      - name: Create file app_store_connect_key.p8
        run: |
          cd ios; cat << EOF >> app_store_connect_key.p8
          ${{ secrets.APP_STORE_CONNECT_AUTH_KEY_P8 }}
          EOF
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Install dependencies
        run: make project/install/package
      - name: Generate l10n
        run: make l10n/generate
      - name: Generate mock file for test
        run: make test/generate/mock-file
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
      - name: Print new build number and run number
        run: echo "Build number is $BUILD_NUMBER, $GITHUB_RUN_NUMBER"
      - name: Increate version code
        run: perl -i -pe 's/^((version:\s+\d+\.\d+\.\d+\+)|(version:\s+\d+\.\d+\.\d+\-\w+\+))(\d+)$/$1.('$GITHUB_RUN_NUMBER')/e' pubspec.yaml
# ios
# test lab
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

#          # create temporary keychain
#          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
#          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#
#          # import certificate to keychain
#          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
#          security list-keychain -d user -s $KEYCHAIN_PATH
#
#          # apply provisioning profile
#          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
#          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
           service_account_key: ${{ secrets.GCP_SA_KEY }}
#      - uses: maierj/fastlane-action@v2.0.1
#        with:
#           lane: 'test_lab'
#           subdirectory: 'ios'
#        env:
#           FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
#           FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
#           SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
#           FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
#           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
#           MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
#           APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
# build file
      - uses: maierj/fastlane-action@v2.0.1
        with:
           lane: 'build_file_for_app_distribution'
           subdirectory: 'ios'
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH: ${{ secrets.seKEYCHAIN_PATH}}
## app distribute
#      - uses: maierj/fastlane-action@v2.0.1
#        with:
#         lane: 'app_distribution_group_developer'
#         subdirectory: 'ios'
#        env:
#         FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
#         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
#         SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
#         FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
##           KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
##           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
## play store
#      - uses: maierj/fastlane-action@v2.0.1
#        with:
#         lane: 'beta'
#         subdirectory: 'ios'
#        env:
#         FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
#         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
#         SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
#         FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
##           KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
##           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
