name: CI/CD fastlane for iOS

on:
#  push:
#  pull_request:
  workflow_dispatch:
    inputs:
      apiUrl:
        description: 'API URL'
        required: true
      ssrUrl:
        description: 'Server send event URL'
        required: true
      grpcWebScheme:
        description: 'GRPC web scheme'
        required: true
      grpcWebDomain:
        description: 'GRPC web domain name'
        required: true
      grpcWebPort:
        description: 'GRPC web running port number'
        required: true
      grpcMobileDomain:
        description: 'GRPC mobile domain name'
        required: true
      grpcMobilePort:
        description: 'GRPC mobile running port number'
        required: true
      websocketUrl:
        description: 'Websocket URL'
        required: true
      branch:
        description: 'Branch trigger workflow'
        required: true

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
      - name: Print new build number and run number
        run: echo "Build number is $BUILD_NUMBER, $GITHUB_RUN_NUMBER"
      - name: Create file .env
        run: |
          cat << EOF >> .env
          API_URL=${{ github.event.inputs.apiUrl }}
          SSR_URL=${{ github.event.inputs.ssrUrl }}
          GRPC_WEB_SCHEME=${{ github.event.inputs.grpcWebScheme }}
          GRPC_WEB_DOMAIN=${{ github.event.inputs.grpcWebDomain }}
          GRPC_WEB_PORT=${{ github.event.inputs.grpcWebPort }}
          GRPC_MOBILE_DOMAIN=${{ github.event.inputs.grpcMobileDomain }}
          GRPC_MOBILE_PORT=${{ github.event.inputs.grpcMobilePort }}
          WEB_SOCKET_URL=${{ github.event.inputs.websocketUrl }}
          EOF
      - name: Create file .env-cicd
        run: |
          cat << EOF >> .env-cicd
          FASTLANE_SLACK_WEB_HOOK=${{ secrets.FASTLANE_SLACK_WEB_HOOK }}
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS=${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS }}
          APP_BUNDLE_ID=${{ secrets.APP_BUNDLE_ID }}
          APPLE_ID=${{ secrets.APPLE_ID }}
          APPLE_ITC_TEAM_ID=${{ secrets.APPLE_ITC_TEAM_ID }}
          APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}
          GIT_URL=${{ secrets.GIT_URL }}
          KEYCHAIN_PASSWORD=${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH=/Users/runner/Library/Keychains/fastlane_tmp_keychain-db
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          CERTIFICATE_PASSWORD=${{ secrets.CERTIFICATE_PASSWORD }}
          DISTRIBUTE_PROFILE_NAME=${{ secrets.DISTRIBUTE_PROFILE_NAME }}
          ADHOC_PROFILE_NAME=${{ secrets.ADHOC_PROFILE_NAME }}
          APP_STORE_CONNECT_AUTH_KEY_ID=${{ secrets.APP_STORE_CONNECT_AUTH_KEY_ID }}
          APP_STORE_CONNECT_AUTH_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_AUTH_ISSUER_ID }}
          BUILD_NUMBER=$BUILD_NUMBER
          EOF
      - name: Create file GoogleService-Info.plist
        run: |
          cd ios; cat << EOF >> GoogleService-Info.plist
          ${{ secrets.GOOGLE_SERVICE_IOS }}
          EOF
      - name: Create file app_store_connect_key.p8
        run: |
          cd ios; cat << EOF >> app_store_connect_key.p8
          ${{ secrets.APP_STORE_CONNECT_AUTH_KEY_P8 }}
          EOF
      - name: Create file distribute_p12_base64.txt
        run: |
          cd ios; cat << EOF >> distribute_p12_base64.txt
          ${{ secrets.DISTRIBUTION_P12_BASE64 }}
          EOF
      - run: base64 -d ios/distribute_p12_base64.txt > ios/distribution.p12
      - name: Create file development_p12_base64.txt
        run: |
          cd ios; cat << EOF >> development_p12_base64.txt
          ${{ secrets.DEVELOPMENT_P12_BASE64 }}
          EOF
      - run: base64 -d ios/distribute_p12_base64.txt > ios/development.p12

      - name: Create file distribute_profile_base64.txt
        run: |
          cd ios; cat << EOF >> distribute_profile_base64.txt
          ${{ secrets.DISTRIBUTE_PROFILE_BASE64 }}
          EOF
      - run: base64 -d ios/distribute_profile_base64.txt > ios/Distribute_comhugemanflutterstarterkit.mobileprovision
      - name: Create file adhoc_profile_base64.txt
        run: |
          cd ios; cat << EOF >> adhoc_profile_base64.txt
          ${{ secrets.ADHOC_PROFILE_BASE64 }}
          EOF
      - run: base64 -d ios/adhoc_profile_base64.txt > ios/AdHoc_comhugemanflutterstarterkit.mobileprovision
      - name: Install dependencies
        run: make project/install/package
      - run: cd ios; pod install
      - name: Generate l10n
        run: make l10n/generate
      - name: Generate mock file for test
        run: make test/generate/mock-file
      # - uses: actions/cache@v2
      #   id: flutter-export-enviroment
      #   with:
      #     path: ./ios/Flutter/flutter_export_enviroment.sh
      #     key: flutter-export-enviroment
      # - uses: actions/cache@v2
      #   id: generated
      #   with:
      #     path: ./ios/Flutter/Generated.xcconfig
      #     key: generated
      # - uses: actions/cache@v2
      #   id: symlinks
      #   with:
      #     path: ./ios/.symlinks
      #     key: symlinks
      # - uses: actions/cache@v2
      #   id: pods
      #   with:
      #     path: ./ios/Pods
      #     key: pods
      # - uses: actions/cache@v2
      #   id: pods-file
      #   with:
      #     path: ./ios/Podfile.lock
      #     key: pods-file
      # - uses: actions/cache@v2
      #   id: file-env
      #   with:
      #     path: ./.env
      #     key: file-env
      # - uses: actions/cache@v2
      #   id: file-env-cicd
      #   with:
      #     path: ./.env-cicd
      #     key: file-env-cicd
      # - uses: actions/cache@v2
      #   id: file-flutter-plugins
      #   with:
      #     path: ./.flutter-plugins
      #     key: file-flutter-plugins
      # - uses: actions/cache@v2
      #   id: file-flutter-plugins-dependency
      #   with:
      #     path: ./.flutter-plugins-dependencies
      #     key: file-flutter-plugins-dependency
      # - uses: actions/cache@v2
      #   id: file-flutter-packages
      #   with:
      #     path: ./.packages
      #     key: file-flutter-packages
      # - uses: actions/cache@v2
      #   id: file-dart-tool
      #   with:
      #     path: ./.dart_tool
      #     key: file-dart-tool
      # - uses: actions/cache@v2
      #   id: file-l10n
      #   with:
      #     path: ./lib/src/configs/l10n
      #     key: file-l10n
      # - uses: actions/cache@v2
      #   id: file-mock-integration-test
      #   with:
      #     path: ./integration_test/main_integration_test.mocks.dart
      #     key: file-mock-integration-test
      # - uses: actions/cache@v2
      #   id: googleService-info-plist
      #   with:
      #     path: ./ios/GoogleService-Info.plist
      #     key: googleService-info-plist
      # - uses: actions/cache@v2
      #   id: app-store-connect-key
      #   with:
      #     path: ./ios/app_store_connect_key.p8
      #     key: app-store-connect-key
      # - uses: actions/cache@v2
      #   id: distribution
      #   with:
      #     path: ./ios/distribution.p12
      #     key: distribution
      # - uses: actions/cache@v2
      #   id: development
      #   with:
      #     path: ./ios/development.p12
      #     key: development
      # - uses: actions/cache@v2
      #   id: distribute-comhugemanflutterstarterkit
      #   with:
      #     path: ./ios/Distribute_comhugemanflutterstarterkit.mobileprovision
      #     key: distribute-comhugemanflutterstarterkit
      # - uses: actions/cache@v2
      #   id: adHoc-comhugemanflutterstarterkit
      #   with:
      #     path: ./ios/AdHoc_comhugemanflutterstarterkit.mobileprovision
      #     key: adHoc-comhugemanflutterstarterkit
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'setup'
          subdirectory: 'ios'
          verbose: true
      - uses: actions/cache@v2
        id: flutter-export-enviroment
        with:
          path: ./ios/Flutter/flutter_export_enviroment.sh
          key: flutter-export-enviroment
      - uses: actions/cache@v2
        id: generated
        with:
          path: ./ios/Flutter/Generated.xcconfig
          key: generated
      - uses: actions/cache@v2
        id: symlinks
        with:
          path: ./ios/.symlinks
          key: symlinks
      - uses: actions/cache@v2
        id: pods
        with:
          path: ./ios/Pods
          key: pods
      - uses: actions/cache@v2
        id: pods-file
        with:
          path: ./ios/Podfile.lock
          key: pods-file
      - uses: actions/cache@v2
        id: file-env
        with:
          path: ./.env
          key: file-env
      - uses: actions/cache@v2
        id: file-env-cicd
        with:
          path: ./.env-cicd
          key: file-env-cicd
      - uses: actions/cache@v2
        id: file-flutter-plugins
        with:
          path: ./.flutter-plugins
          key: file-flutter-plugins
      - uses: actions/cache@v2
        id: file-flutter-plugins-dependency
        with:
          path: ./.flutter-plugins-dependencies
          key: file-flutter-plugins-dependency
      - uses: actions/cache@v2
        id: file-flutter-packages
        with:
          path: ./.packages
          key: file-flutter-packages
      - uses: actions/cache@v2
        id: file-dart-tool
        with:
          path: ./.dart_tool
          key: file-dart-tool
      - uses: actions/cache@v2
        id: file-l10n
        with:
          path: ./lib/src/configs/l10n
          key: file-l10n
      - uses: actions/cache@v2
        id: file-mock-integration-test
        with:
          path: ./integration_test/main_integration_test.mocks.dart
          key: file-mock-integration-test
      - uses: actions/cache@v2
        id: googleService-info-plist
        with:
          path: ./ios/GoogleService-Info.plist
          key: googleService-info-plist
      - uses: actions/cache@v2
        id: app-store-connect-key
        with:
          path: ./ios/app_store_connect_key.p8
          key: app-store-connect-key
      - uses: actions/cache@v2
        id: distribution
        with:
          path: ./ios/distribution.p12
          key: distribution
      - uses: actions/cache@v2
        id: development
        with:
          path: ./ios/development.p12
          key: development
      - uses: actions/cache@v2
        id: distribute-comhugemanflutterstarterkit
        with:
          path: ./ios/Distribute_comhugemanflutterstarterkit.mobileprovision
          key: distribute-comhugemanflutterstarterkit
      - uses: actions/cache@v2
        id: adHoc-comhugemanflutterstarterkit
        with:
          path: ./ios/AdHoc_comhugemanflutterstarterkit.mobileprovision
          key: adHoc-comhugemanflutterstarterkit
      - uses: actions/cache@v2
        id: keychain-ci-cd
        with:
          path:  ~/Library/Keychains/cicd.keychain-db
          key: keychain-ci-cd
      - uses: actions/cache@v2
        id: keychain-login
        with:
          path:  /Users/runner/Library/Keychains/login.keychain-db
          key: keychain-login
      - uses: actions/cache@v2
        id: provisioning-profile
        with:
          path: ~/Library/MobileDevice/Provisioning\ Profiles
          key: provisioning-profile
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@master
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#      - uses: maierj/fastlane-action@v2.0.1
#        with:
#          lane: 'test_lab'
#          subdirectory: 'ios'
#          verbose: true
#        env:
#          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
#          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
#          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
#          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
#          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
#          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
#          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
#          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
#          KEYCHAIN_PATH: ${{ secrets.KEYCHAIN_PATH}}
#          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
#       - uses: maierj/fastlane-action@v2.0.1
#         with:
#           lane: 'build_file_for_distribution'
#           subdirectory: 'ios'
#           verbose: true
#       - uses: maierj/fastlane-action@v2.0.1
#         with:
#           lane: 'build_file_for_app_distribution'
#           subdirectory: 'ios'
#           verbose: true
#       - uses: maierj/fastlane-action@v2.0.1
#         with:
#           lane: 'app_distribution_group_developer_qa' # can run specific group for test with input
#           subdirectory: 'ios'
#           verbose: true
#       - run: cd ios; ls -la
# #      - run: cd ios/build; ls -la
#       - uses: maierj/fastlane-action@v2.0.1
#         with:
#           lane: 'release'
#           subdirectory: 'ios'
#           verbose: true
#       - run: cd ios; ls -la
#       - uses: actions/cache@v2
#         id: file-ipa-for-distribute
#         with:
#           path: ./ios/Runner.ipa
#           key: file-ipa-for-distribute




  build_ipa:
    needs: [ setup ]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/cache@v2
        id: file-env
        with:
          path: ./.env
          key: file-env
      - uses: actions/cache@v2
        id: file-env-cicd
        with:
          path: ./.env-cicd
          key: file-env-cicd
      - uses: actions/cache@v2
        id: file-flutter-plugins
        with:
          path: ./.flutter-plugins
          key: file-flutter-plugins
      - uses: actions/cache@v2
        id: file-flutter-plugins-dependency
        with:
          path: ./.flutter-plugins-dependencies
          key: file-flutter-plugins-dependency
      - uses: actions/cache@v2
        id: file-flutter-packages
        with:
          path: ./.packages
          key: file-flutter-packages
      - uses: actions/cache@v2
        id: file-dart-tool
        with:
          path: ./.dart_tool
          key: file-dart-tool
      - uses: actions/cache@v2
        id: file-l10n
        with:
          path: ./lib/src/configs/l10n
          key: file-l10n
      - uses: actions/cache@v2
        id: googleService-info-plist
        with:
          path: ./ios/GoogleService-Info.plist
          key: googleService-info-plist
      - uses: actions/cache@v2
        id: app-store-connect-key
        with:
          path: ./ios/app_store_connect_key.p8
          key: app-store-connect-key
      - uses: actions/cache@v2
        id: distribution
        with:
          path: ./ios/distribution.p12
          key: distribution
      - uses: actions/cache@v2
        id: development
        with:
          path: ./ios/development.p12
          key: development
      - uses: actions/cache@v2
        id: distribute-comhugemanflutterstarterkit
        with:
          path: ./ios/Distribute_comhugemanflutterstarterkit.mobileprovision
          key: distribute-comhugemanflutterstarterkit
      - uses: actions/cache@v2
        id: adHoc-comhugemanflutterstarterkit
        with:
          path: ./ios/AdHoc_comhugemanflutterstarterkit.mobileprovision
          key: adHoc-comhugemanflutterstarterkit
      - uses: actions/cache@v2
        id: pods
        with:
          path: ./ios/Pods
          key: pods
      - uses: actions/cache@v2
        id: pods-file
        with:
          path: ./ios/Podfile.lock
          key: pods-file
      - uses: actions/cache@v2
        id: flutter-export-enviroment
        with:
          path: ./ios/Flutter/flutter_export_enviroment.sh
          key: flutter-export-enviroment
      - uses: actions/cache@v2
        id: generated
        with:
          path: ./ios/Flutter/Generated.xcconfig
          key: generated
      - uses: actions/cache@v2
        id: symlinks
        with:
          path: ./ios/.symlinks
          key: symlinks
      - run: make project/install/package
      - uses: actions/cache@v2
        id: keychain-ci-cd
        with:
          path:  ~/Library/Keychains/cicd.keychain-db
          key: keychain-ci-cd
      - uses: actions/cache@v2
        id: provisioning-profile
        with:
          path: ~/Library/MobileDevice/Provisioning\ Profiles
          key: provisioning-profile
      - uses: actions/cache@v2
        id: keychain-login
        with:
          path:  /Users/runner/Library/Keychains/login.keychain-db
          key: keychain-login
      # - uses: maierj/fastlane-action@v2.0.1
      #   with:
      #     lane: 'setup'
      #     subdirectory: 'ios'
      #     verbose: true
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'build_file_for_distribution'
          subdirectory: 'ios'
          verbose: true
      # - name: Run mobSF
      #   env:
      #     MOBSF_URL: ${{ secrets.MOBSF_URL }}
      #     MOBSF_API_KEY: ${{ secrets.MOBSF_API_KEY }}
      #   run: export MOBSF_URL=$MOBSF_URL; export MOBSF_API_KEY=$MOBSF_API_KEY; export INPUT_FILE_NAME='ios/a.ipa'; make mobsf/run



# clean credential file

  mobSF:
    runs-on: ubuntu-latest
    needs: [ setup, build_ipa ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: file-ipa-for-distribute
        with:
          path: ./ios/Runner.ipa
          key: file-ipa-for-distribute
      - run: cd ios; ls -la
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: '.github/vpn/config.ovpn'
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Post API with private domain
        env:
          MOBSF_URL: ${{ secrets.MOBSF_URL }}
        run: |
          sudo sh -c "echo nameserver 172.31.0.2 > /etc/resolv.conf"
          curl -vvv $MOBSF_URL/api/v1/scan
      - name: Run mobSF
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'mobSF'
          subdirectory: 'ios'
        env:
          MOBSF_URL: ${{ secrets.MOBSF_URL }}
          MOBSF_API_KEY: ${{ secrets.MOBSF_API_KEY }}
      - name: kill vpn
        if: always()
        run: sudo killall openvpn

  notify_slack_success:
    runs-on: ubuntu-latest
    needs: [ setup, build_ipa, mobSF ]
    if: success()
    steps:
      - name: Notify test result
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#90be6d'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Job is success

  notify_slack_failure:
    runs-on: ubuntu-latest
    needs: [ setup, build_ipa, mobSF ]
    if: failure()
    steps:
      - name: Notify test result
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#f94144'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Job is failure
