name: CI/CD fastlane for iOS

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter version stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Create file .env
        run: |
          cat << EOF >> .env
          API_URL=${{ secrets.API_URL_DEV }}
          FASTLANE_SLACK_WEB_HOOK=${{ secrets.FASTLANE_SLACK_WEB_HOOK }}
          FASTLANE_SLACK_CHANNEL=${{ secrets.FASTLANE_SLACK_CHANNEL }}
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID=${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID }}
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS=${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_IOS }}
          APP_BUNDLE_ID=${{ secrets.APP_BUNDLE_ID }}
          APPLE_ID=${{ secrets.APPLE_ID }}
          APPLE_ITC_TEAM_ID=${{ secrets.APPLE_ITC_TEAM_ID }}
          APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}
          APPLE_PROVISIONING_PROFILE_DISTRIBUTE=${{ secrets.APPLE_PROVISIONING_PROFILE_DISTRIBUTE }}
          APPLE_PROVISIONING_PROFILE_ADHOC=${{ secrets.APPLE_PROVISIONING_PROFILE_ADHOC }}
          GRPC_HOST=${{ secrets.GRPC_HOST }}
          GRPC_PORT=${{ secrets.GRPC_PORT }}
          GRPC_SCHEME=${{ secrets.GRPC_SCHEME }}
          FASTLANE_FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_SERVICES_AC_JSON_DATA=${{ secrets.PLAY_STORE_CREDENTIALS }}
          GIT_URL=${{ secrets.GIT_URL }}
          MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME=${{ secrets.MATCH_USERNAME }}
          FASTLANE_SESSION=${{ secrets.FASTLANE_SESSION }}
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER=${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
          APP_BUNDLE_ID=${{ secrets.APP_BUNDLE_ID }}
          KEYCHAIN_PASSWORD=${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH=/Users/runner/Library/Keychains/fastlane_tmp_keychain-db
          APPLE_PASSWORD=${{ secrets.APPLE_PASSWORD }}
          APP_STORE_CONNECT_AUTH_KEY_ID=${{ secrets.APP_STORE_CONNECT_AUTH_KEY_ID}}
          APP_STORE_CONNECT_AUTH_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_AUTH_ISSUER_ID }}
          P12_PASSWORD=${{ secrets.P12_PASSWORD }}
          EOF
      - name: Create file GoogleService-Info.plist
        run: |
          cd ios; cat << EOF >> GoogleService-Info.plist
          ${{ secrets.GOOGLE_SERVICE_IOS }}
          EOF
      - name: Install dependencies
        run: make project/install/package
      - name: Generate l10n
        run: make l10n/generate
      - name: Generate mock file for test
        run: make test/generate/mock-file
      - uses: maierj/fastlane-action@v2.0.1
        with:
           lane: 'build_file_for_app_distribution'
           subdirectory: 'ios'
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH: ${{ secrets.KEYCHAIN_PATH}}
