name: Manually triggered workflow test
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
      - run: echo "Deploying on branch $GITHUB_REF"
      - run: echo "__ ${{ github.ref_name }}"
      - run: echo "__ ${{ github.ref }}"
      - run: echo "__ ${{ github.base_ref }}"
      - run: echo "__ ${{ github.head_ref }}"
      - run: echo "__ ${{ github.ref_protected }}"
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: "${{ github.event.inputs.name }}"
          subdirectory: 'android'
        env:
          FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID: ${{ secrets.FASTLANE_FIREBASE_APP_DISTRIBUTE_ID_ANDROID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


  feature:
    if: ${{ github.ref == 'refs/heads/feature/*' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying on branch $GITHUB_REF"

  main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying on branch $GITHUB_REF"